# .github/workflows/build-pdf.yml
name: Build PDFs from Markdown

# ── Trigger the workflow on every push to the main branch (add others if you like)
on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣  Install Pandoc + a TeX engine that includes xelatex
      - name: Install Pandoc and TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-extra

      # 3️⃣  Convert your Markdown file to PDF
      - name: Convert Markdown ➜ PDF
        run: |
          pandoc Unified_Scaffold_Final_Condensed.md \
                 --pdf-engine=xelatex \
                 -o Unified_Scaffold_Final_Condensed.pdf

      # 4️⃣  Upload the generated PDF as a workflow artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: scaffold-paper-pdf
          path: Unified_Scaffold_Final_Condensed.pdf
