# .github/workflows/build-pdf.yml
name: Build PDFs from Markdown

# ── Run this workflow on every push to your main branch.
on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣  Install Pandoc, TeX Live (with xelatex), and rsvg-convert for SVG images
      - name: Install Pandoc, TeX Live, and SVG converter
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex texlive-fonts-recommended texlive-latex-extra \
            librsvg2-bin      # ← supplies rsvg-convert required for SVG badges

      # 3️⃣  Convert your Markdown file to PDF
      - name: Convert Markdown ➜ PDF
        run: |
          pandoc Unified_Scaffold_Final_Condensed.md \
                 --pdf-engine=xelatex \
                 -o Unified_Scaffold_Final_Condensed.pdf

      # 4️⃣  Upload the generated PDF as a workflow artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: scaffold-paper-pdf
          path: Unified_Scaffold_Final_Condensed.pdf
