# .github/workflows/build-pdf.yml
name: Build PDFs from Markdown

on:
  push:
    branches: ["main", "master"]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣  Check out your repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣  Write a Lua filter that drops remote images (http/https)
      - name: Create skip-remote-img.lua
        run: |
          cat <<'LUA' > skip-remote-img.lua
          function Image(img)
            if img.src:match('^https?://') then
              return {}         -- delete the image node
            end
            return img          -- keep local images
          end
          LUA

      # 3️⃣  Install Pandoc, TeX Live (with xelatex) and rsvg-convert
      - name: Install Pandoc, TeX, rsvg-convert
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex texlive-fonts-recommended texlive-latex-extra \
            librsvg2-bin

      # 4️⃣  Convert the original Markdown to PDF, skipping remote images
      - name: Convert Markdown ➜ PDF
        run: |
          pandoc Unified_Scaffold_Final_Condensed.md \
                 --lua-filter=skip-remote-img.lua \
                 --pdf-engine=xelatex \
                 -o Unified_Scaffold_Final_Condensed.pdf

      # 5️⃣  Upload the generated PDF
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: scaffold-paper-pdf
          path: Unified_Scaffold_Final_Condensed.pdf
